### ISSUE TITLE
inject cpu fail failed to execute /tmp/chaosmetad-0.5.1/chaosmetad: No such file or directory

### ISSUE THREAD

**Issue by wujunwei** [traas-stack/chaosmeta#155]
When use chaosmeta to inject pod cpu fault, it failed and shows 
```
phase: inject
status: failed
message: create failed
detail:
  inject:
  - injectobjectname: pod/default/static-web/web
    uid: "202402271149102723"
    message: |
      experiment inject error: kubectl exec error: exec remote cmd error: command terminated with exit code 1  nsenter: failed to execute /tmp/chaosmetad-0.5.1/chaosmetad: No such file or directory
    status: failed
    starttime: "2024-02-27 11:49:10"
    updatetime: ""
    backup: ""
  recover: []
createtime: "2024-02-27 11:49:10"
updatetime: "2024-02-27 11:49:11"

```
How can I fix this?
Releative logs in chaosmeta-inject-controller-manager
```
2024-02-27T11:54:11Z    INFO    experiment: chaosmeta/inject-fault-pod-cpu-e-176244443868194816021709034473node, get status: {"phase":"recover","status":"created","message":"create failed","detail":{"inject":[{"injectObjectName":"pod/default/static-web/web","uid":"202402271149102723","message":"experiment inject error: kubectl exec error: exec remote cmd error: command terminated with exit code 1  nsenter: failed to execute /tmp/chaosmetad-0.5.1/chaosmetad: No such file or directory\n","status":"failed","startTime":"2024-02-27 11:49:10"}],"recover":[{"injectObjectName":"pod/default/static-web/web","uid":"202402271149102723","message":"start to recover","status":"created","startTime":"2024-02-27 11:54:11"}]},"createTime":"2024-02-27 11:49:10","updateTime":"2024-02-27 11:54:11"} {"controller": "experiment", "controllerGroup": "chaosmeta.io", "controllerKind": "Experiment", "Experiment": {"name":"inject-fault-pod-cpu-e-176244443868194816021709034473node","namespace":"chaosmeta"}, "namespace": "chaosmeta", "name": "inject-fault-pod-cpu-e-176244443868194816021709034473node", "reconcileID": "ae672cac-1283-4d38-b800-1d93da739e12"}
```
